global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/recording-rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: payment-api
    metrics_path: /metrics/payment-api
    static_configs:
      - targets: ["metrics-proxy:3003"]
  - job_name: payment-worker
    metrics_path: /metrics/payment-worker
    static_configs:
      - targets: ["metrics-proxy:3003"]
